networks:
  frontend:
    name: ${COMPOSE_PROJECT_NAME:-api}_frontend-${ENVIRONMENT:-prod}
  backend:
    name: ${COMPOSE_PROJECT_NAME:-api}_backend-${ENVIRONMENT:-prod}
    internal: true  # No external access

services:
  redis:
    container_name: ${COMPOSE_PROJECT_NAME:-api}-redis-${ENVIRONMENT:-prod}
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - backend

  web:
    container_name: ${COMPOSE_PROJECT_NAME:-api}-web-${ENVIRONMENT:-prod}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - env.prod
    depends_on:
      - db
    entrypoint: ["/app/devops/scripts/start-prod.sh"]
    networks:
      - frontend
      - backend

  db:
    env_file:
      - env.prod
    container_name: ${COMPOSE_PROJECT_NAME:-api}-db-${ENVIRONMENT:-prod}
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  redis_data:
  postgres_data: