"""initial

Revision ID: 62af5c82d8c9
Revises:
Create Date: 2025-02-10 21:37:37.976089

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62af5c82d8c9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
